---

    - name: Install Vim
      package:
        name: vim
        state: present

    - name: Install Python3
      package:
        name: python3
        state: present

    - name: Install Curl
      package:
        name: curl
        state: present

    - name: Installing lvm2 utils
      package:
        name: lvm2
        state: present

    - name: Installing ufw
      package:
        name: ufw
        state: present

    - name: Allow everything and enable UFW
      community.general.ufw:
        state: enabled
        policy: allow

    - name: Install pip
      apt:
        name: python3-pip
        update_cache: true
        state: present
      #async: 60
      #poll: 60

    - name: Install k3s pre-requisites
      pip:
        name:
        - openshift
        - pyyaml
        - kubernetes

    - name: Install helm if not exists
      unarchive:
        src: "{{ helm_install_url }}"
        dest: /usr/local/bin
        extra_opts: "--strip-components=1"
        owner: root
        group: root
        mode: 0755
        remote_src: true
      args:
        creates: /usr/local/bin/helm