---

- name: Add bitnami's chart repository
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "{{ bitnami_repo_url }}"

- name: Deploy helm chart
  kubernetes.core.helm:
    name: keycloak
    chart_ref: bitnami/keycloak
    release_namespace: keycloak
    kubeconfig: "{{ kubeconfig_path }}"
    values:
      ingress:
        enabled: true
