---

- name: Creating pv
  shell: "sudo pvcreate {{ disk_name }}"
  when: lvm_ebs

- name: Creating volume group
  shell: "sudo vgcreate {{vg_name}} {{ disk_name }}"
  when: lvm_ebs

- name: Creating directory for hostpath
  file:
    path: /var/openebs/local
    state: directory
  when: hostpath_ebs

- name: Installing OpenEBS LVM
  shell: "kubectl apply -f https://raw.githubusercontent.com/openebs/charts/gh-pages/versioned/{{ openebs_version }}/lvm-operator.yaml"


- name: Creating Storage Class
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    definition:
      api_version: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: openebs-lvmpv
      parameters:
        storage: "lvm"
        volgroup: "{{ vg_name }}"
      provisioner: local.csi.openebs.io
  when: lvm_ebs

#- name: Creating Storage Class
#  kubernetes.core.k8s:
#    state: present
#    kubeconfig: "{{ kubeconfig_path }}"
#    definition:
#      apiVersion: storage.k8s.io/v1
#      kind: StorageClass
#      metadata:
#        name: local-hostpath
#        annotations:
#          openebs.io/cas-type: local
#          cas.openebs.io/config: |
#            - name: StorageType
#              value: hostpath
#            - name: BasePath
#              value: /var/local-hostpath
#      provisioner: openebs.io/local
#      reclaimPolicy: Delete
#      volumeBindingMode: WaitForFirstConsumer


- name: Creating hostpath PVC
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: openebs-hostpath
        namespace: keycloak
      spec:
        storageClassName: openebs-hostpath
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "{{ requested_storage }}"
  when: hostpath_ebs

- name: Creating lvm PVC
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: csi-lvmpv
      spec:
        storageClassName: openebs-lvmpv
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
          storage: "{{ requested_storage }}"
  when: lvm_ebs