---

- name: Install k3s
  shell: "curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -s -"
  become: true

- name: Chmod
  file:
    path: "{{ kubeconfig_path }}"
    mode: '0644'
  become: true

- name: Register srv
  command: "hostname"
  register: hostname

- name: Allowing external connections to k3s
  command: "sed -i 's/127.0.0.1/{{ hostname.stdout }}/g' /etc/rancher/k3s/k3s.yaml"


- name: Fetching kubeconfig
  fetch:
    src: "{{ kubeconfig_path }}"
    dest: fetched/kubeconfig

- name: Creating a namespace
  kubernetes.core.k8s:
    name: keycloak
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ kubeconfig_path }}"