---

- name: Install k3s
  shell: curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s -
  become: true

- name: Chmod
  file:
    path: "{{ kubeconfig_path }}"
    mode: '0644'
  become: true

- name: Allowing external connections to k3s
  shell: sed -i -e '/certificate-authority-data:/d' -e '/server:/s@https://127.0.0.1:6443@k3s.cluster.local:6443@' -e '4a\ \ \ \ insecure-skip-tls-verify:\ true' /etc/rancher/k3s/k3s.yaml

- name: Fetching kubeconfig
  fetch:
    src: "{{ kubeconfig_path }}"
    dest: fetched/kubeconfig

- name: Creating a namespace
  kubernetes.core.k8s:
    name: keycloak
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ kubeconfig_path }}"