---

- name: Install k3s
  shell: curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s -
  become: true

- name: Chmod
  file:
    path: /etc/rancher/k3s/k3s.yaml
    mode: '0644'
  become: true
